apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: web-api-so-ip-allowlist
  labels:
    app.kubernetes.io/name: web-api-so
    app.kubernetes.io/part-of: dialogporten
spec:
  ipAllowList:
    sourceRange:
      - 0.0.0.0/32
