apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
commonLabels:
  app.kubernetes.io/name: web-api-so
  app.kubernetes.io/part-of: dialogporten
patchesStrategicMerge:
  - patches.yaml
