apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dialogporten
resources:
  - ../../manifests/common/base
  - ../../manifests/apps/web-api-eu/environments/yt01
  - ../../manifests/apps/web-api-so/environments/yt01
  - ../../manifests/apps/graphql/environments/yt01
  - ../../manifests/apps/service/environments/yt01
  - ../../manifests/jobs/web-api-migration-job/environments/yt01
  - ../../manifests/jobs/sync-resource-policy-information-job/environments/yt01
  - ../../manifests/jobs/sync-subject-resource-mappings-job/environments/yt01
  - ../../manifests/jobs/reindex-dialogsearch-job/environments/yt01
  - ../../manifests/jobs/aggregate-cost-metrics-job/environments/yt01
images:
  - name: ghcr.io/altinn/dialogporten-webapi
    newTag: v.1.100.1
  - name: ghcr.io/altinn/dialogporten-graphql
    newTag: v.1.100.1
  - name: ghcr.io/altinn/dialogporten-service
    newTag: v.1.100.1
  - name: ghcr.io/altinn/dialogporten-migration-bundle
    newTag: v.1.100.1
  - name: ghcr.io/altinn/dialogporten-janitor
    newTag: v.1.100.1
