apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-eu
spec:
  template:
    spec:
      containers:
        - name: web-api-eu
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: yt01
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-api-eu-runtime
  labels:
    app.kubernetes.io/instance: yt01
data:
  DIALOGPORTEN_ENVIRONMENT: yt01
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web-api-eu-secrets
  labels:
    app.kubernetes.io/instance: yt01
