apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/web-api-so/base
patchesStrategicMerge:
  - allowlist.yaml
  - deployment-env.yaml
  - deployment-resources.yaml
