apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dialogporten-apps-yt01
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environments/yt01
  prune: true
  sourceRef:
    kind: OCIRepository
    name: dialogporten-manifests-yt01
  targetNamespace: dialogporten
