apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  labels:
    app.kubernetes.io/name: graphql
    app.kubernetes.io/part-of: dialogporten
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: graphql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: graphql
        app.kubernetes.io/part-of: dialogporten
    spec:
      serviceAccountName: graphql
      containers:
        - name: graphql
          image: ghcr.io/altinn/dialogporten-graphql:set-by-ci
---
apiVersion: v1
kind: Service
metadata:
  name: graphql
  labels:
    app.kubernetes.io/name: graphql
    app.kubernetes.io/part-of: dialogporten
spec:
  selector:
    app.kubernetes.io/name: graphql
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: graphql
  labels:
    app.kubernetes.io/name: graphql
    app.kubernetes.io/part-of: dialogporten
spec:
  routes:
    - match: Host(`placeholder.invalid`) && PathPrefix(`/dialogporten/graphql`)
      priority: 20
      middlewares:
        - name: graphql-ip-allowlist
      services:
        - name: graphql
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: graphql-ip-allowlist
  labels:
    app.kubernetes.io/name: graphql
    app.kubernetes.io/part-of: dialogporten
spec:
  ipAllowList:
    sourceRange:
      - 0.0.0.0/32
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: graphql
  labels:
    app.kubernetes.io/name: graphql
    app.kubernetes.io/part-of: dialogporten
spec:
  scaleTargetRef:
    name: graphql
---
apiVersion: application.dis.altinn.cloud/v1alpha1
kind: ApplicationIdentity
metadata:
  name: graphql
  labels:
    app.kubernetes.io/name: graphql
    app.kubernetes.io/part-of: dialogporten
