apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  labels:
    app.kubernetes.io/name: graphql
    app.kubernetes.io/part-of: dialogporten
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: graphql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: graphql
        app.kubernetes.io/part-of: dialogporten
    spec:
      serviceAccountName: graphql
      containers:
        - name: graphql
          image: ghcr.io/altinn/dialogporten-graphql:set-by-ci
          envFrom:
            - configMapRef:
                name: graphql-runtime
          env:
            - name: Infrastructure__DialogDbConnectionString
              valueFrom:
                secretKeyRef:
                  name: graphql-secrets
                  key: dialogportenAdoConnectionString
            - name: Infrastructure__Redis__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: graphql-secrets
                  key: dialogportenRedisConnectionString
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-runtime
  labels:
    app.kubernetes.io/name: graphql
    app.kubernetes.io/part-of: dialogporten
data:
  AZURE_APPCONFIG_URI: ${DIALOGPORTEN_AZURE_APPCONFIG_URI}
  Infrastructure__MassTransit__Host: ${DIALOGPORTEN_SERVICEBUS_HOST}
  DIALOGPORTEN_ENVIRONMENT: set-by-env
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: graphql-secrets
  labels:
    app.kubernetes.io/name: graphql
    app.kubernetes.io/part-of: dialogporten
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: dialogporten-azure-kv
  target:
    name: graphql-secrets
    creationPolicy: Owner
  data:
    - secretKey: dialogportenAdoConnectionString
      remoteRef:
        key: dialogportenAdoConnectionString
    - secretKey: dialogportenRedisConnectionString
      remoteRef:
        key: dialogportenRedisConnectionString
---
apiVersion: v1
kind: Service
metadata:
  name: graphql
  labels:
    app.kubernetes.io/name: graphql
    app.kubernetes.io/part-of: dialogporten
spec:
  selector:
    app.kubernetes.io/name: graphql
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: graphql
  labels:
    app.kubernetes.io/name: graphql
    app.kubernetes.io/part-of: dialogporten
spec:
  routes:
    - match: PathPrefix(`/dialogporten/graphql`)
      priority: 20
      middlewares:
        - name: graphql-ip-allowlist
      services:
        - name: graphql
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: graphql-ip-allowlist
  labels:
    app.kubernetes.io/name: graphql
    app.kubernetes.io/part-of: dialogporten
spec:
  ipAllowList:
    sourceRange:
      - 0.0.0.0/32
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: graphql
  labels:
    app.kubernetes.io/name: graphql
    app.kubernetes.io/part-of: dialogporten
spec:
  scaleTargetRef:
    name: graphql
---
apiVersion: application.dis.altinn.cloud/v1alpha1
kind: ApplicationIdentity
metadata:
  name: graphql
  labels:
    app.kubernetes.io/name: graphql
    app.kubernetes.io/part-of: dialogporten
spec: {}
