apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dialogporten
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux-system/at23
  prune: true
  sourceRef:
    kind: GitRepository
    name: dialogporten
  targetNamespace: flux-system
