apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dialogporten
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/dialogporten/overlays/at23
  prune: true
  sourceRef:
    kind: GitRepository
    name: dialogporten
  postBuild:
    substituteFrom:
      - kind: Secret
        name: dialogporten-flux-substitutions
        optional: true
      - kind: ConfigMap
        name: dialogporten-flux-substitutions
        optional: false
  targetNamespace: dialogporten
