apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dialogporten
  namespace: dialogporten
spec:
  interval: 10m
  path: ./flux-system/at23
  prune: true
  sourceRef:
    kind: OCIRepository
    name: dialogporten
  targetNamespace: dialogporten
