apiVersion: kustomize.toolkit.fluxcd.io/v1beta3
kind: Kustomization
metadata:
  name: dialogporten-apps-at23
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environments/at23
  prune: true
  sourceRef:
    kind: OCIRepository
    name: dialogporten-manifests-at23
  targetNamespace: dialogporten
  postBuild:
    substituteFrom:
      - kind: Secret
        name: dialogporten-flux-substitutions
        optional: true
      - kind: ConfigMap
        name: dialogporten-flux-substitutions
        optional: false
