apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dialogporten-apps-at23
  namespace: dialogporten
spec:
  interval: 10m0s
  path: ./environments/at23
  prune: true
  sourceRef:
    kind: OCIRepository
    name: dialogporten-manifests-at23
  targetNamespace: dialogporten
