apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dialogporten-apps-tt02
  namespace: dialogporten
spec:
  interval: 10m0s
  path: ./environments/tt02
  prune: true
  sourceRef:
    kind: OCIRepository
    name: dialogporten-manifests-tt02
  targetNamespace: dialogporten
