apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
spec:
  template:
    spec:
      containers:
        - name: graphql
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: staging
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-runtime
  labels:
    app.kubernetes.io/instance: tt02
data:
  DIALOGPORTEN_ENVIRONMENT: staging
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: graphql-secrets
  labels:
    app.kubernetes.io/instance: tt02
