apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-so
  labels:
    app.kubernetes.io/name: web-api-so
    app.kubernetes.io/part-of: dialogporten
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: web-api-so
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-api-so
        app.kubernetes.io/part-of: dialogporten
    spec:
      serviceAccountName: web-api-so
      containers:
        - name: web-api-so
          image: ghcr.io/altinn/dialogporten-webapi:set-by-ci
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-api-so
  labels:
    app.kubernetes.io/name: web-api-so
    app.kubernetes.io/part-of: dialogporten
spec:
  selector:
    app.kubernetes.io/name: web-api-so
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web-api-so
  labels:
    app.kubernetes.io/name: web-api-so
    app.kubernetes.io/part-of: dialogporten
spec:
  routes:
    - match: Host(`placeholder.invalid`) && PathPrefix(`/dialogporten`)
      priority: 1
      middlewares:
        - name: web-api-so-ip-allowlist
      services:
        - name: web-api-so
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: web-api-so-ip-allowlist
  labels:
    app.kubernetes.io/name: web-api-so
    app.kubernetes.io/part-of: dialogporten
spec:
  ipAllowList:
    sourceRange:
      - 0.0.0.0/32
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-api-so
  labels:
    app.kubernetes.io/name: web-api-so
    app.kubernetes.io/part-of: dialogporten
spec:
  scaleTargetRef:
    name: web-api-so
---
apiVersion: application.dis.altinn.cloud/v1alpha1
kind: ApplicationIdentity
metadata:
  name: web-api-so
  labels:
    app.kubernetes.io/name: web-api-so
    app.kubernetes.io/part-of: dialogporten
