apiVersion: application.dis.altinn.cloud/v1alpha1
kind: ApplicationIdentity
metadata:
  name: dialogporten-secrets
  namespace: dialogporten
  labels:
    app.kubernetes.io/part-of: dialogporten
spec: {}