apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-so
spec:
  template:
    spec:
      containers:
        - name: web-api-so
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: staging
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1"
