apiVersion: v1
kind: Service
metadata:
  name: web-api-so
  labels:
    app.kubernetes.io/name: web-api-so
    app.kubernetes.io/part-of: dialogporten
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web-api-so
  ports:
    - name: http
      port: 80
      targetPort: 8080
