apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-eu
spec:
  template:
    spec:
      serviceAccountName: web-api-eu
      containers:
        - name: web-api-eu
          image: ghcr.io/altinn/dialogporten-webapi:set-by-ci
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web-api-eu
spec:
  routes:
    - match: Host(`placeholder.invalid`) && PathPrefix(`/dialogporten/enduser`)
      priority: 10
      middlewares:
        - name: web-api-eu-ip-allowlist
      services:
        - name: web-api-eu
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: web-api-eu-ip-allowlist
---
apiVersion: v1
kind: Service
metadata:
  name: web-api-eu
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-api-eu
spec:
  scaleTargetRef:
    name: web-api-eu
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: application.dis.altinn.cloud/v1alpha1
kind: ApplicationIdentity
metadata:
  name: web-api-eu
