apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: dialogporten-azure-kv
  namespace: dialogporten
spec:
  provider:
    azurekv:
      vaultUrl: https://dp-be-test-kv-yju3bdib4d.vault.azure.net/
