apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
spec:
  template:
    spec:
      serviceAccountName: graphql
      containers:
        - name: graphql
          image: ghcr.io/altinn/dialogporten-graphql:set-by-ci
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: graphql
spec:
  routes:
    - match: Host(`placeholder.invalid`) && PathPrefix(`/dialogporten/graphql`)
      priority: 20
      middlewares:
        - name: graphql-ip-allowlist
      services:
        - name: graphql
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: graphql-ip-allowlist
---
apiVersion: v1
kind: Service
metadata:
  name: graphql
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: graphql
spec:
  scaleTargetRef:
    name: graphql
---
apiVersion: application.dis.altinn.cloud/v1alpha1
kind: ApplicationIdentity
metadata:
  name: graphql
