apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
spec:
  template:
    spec:
      containers:
        - name: graphql
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: prod
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "0.2"
