apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: dialogporten-azure-kv
  namespace: dialogporten
spec:
  provider:
    azurekv:
      vaultUrl: https://dp-be-yt01-kv-52fstq2krm.vault.azure.net/
