apiVersion: batch/v1
kind: CronJob
metadata:
  name: web-api-migration-job
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: web-api-migration-job
              env:
                - name: DOTNET_ENVIRONMENT
                  value: prod
