apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: dialogporten
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: service
  ports:
    - name: http
      port: 80
      targetPort: 8080
