apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/web-api-so/base
patches:
  - path: allowlist.yaml
  - path: deployment-env.yaml
  - path: deployment-resources.yaml
  - path: hpa-min.yaml
