apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dialogporten
resources:
  - ../../common/base
  - apps
  - jobs
patches:
  - path: secretstore-vault-url.yaml
images:
  - name: ghcr.io/altinn/dialogporten-webapi
    newTag: 1.105.1
  - name: ghcr.io/altinn/dialogporten-graphql
    newTag: 1.105.1
  - name: ghcr.io/altinn/dialogporten-service
    newTag: 1.105.1
  - name: ghcr.io/altinn/dialogporten-migration-bundle
    newTag: 1.105.1
  - name: ghcr.io/altinn/dialogporten-janitor
    newTag: 1.105.1
