apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-eu
  labels:
    app.kubernetes.io/name: web-api-eu
    app.kubernetes.io/part-of: dialogporten
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-api-eu
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-api-eu
        app.kubernetes.io/part-of: dialogporten
    spec:
      serviceAccountName: web-api-eu
      containers:
        - name: web-api-eu
          image: ghcr.io/altinn/dialogporten-webapi:set-by-ci
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: set-by-env
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              value: ${DIALOGPORTEN_APPINSIGHTS_CONNECTION_STRING}
            - name: AZURE_APPCONFIG_URI
              valueFrom:
                configMapKeyRef:
                  name: dialogporten-runtime
                  key: AZURE_APPCONFIG_URI
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: OTEL_TRACES_SAMPLER
              value: parentbased_traceidratio
            - name: OTEL_TRACES_SAMPLER_ARG
              value: set-by-env
          startupProbe:
            httpGet:
              path: /health/startup
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 2
