apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-eu
  labels:
    app.kubernetes.io/name: web-api-eu
    app.kubernetes.io/part-of: dialogporten
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: web-api-eu
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-api-eu
        app.kubernetes.io/part-of: dialogporten
    spec:
      serviceAccountName: web-api-eu
      containers:
        - name: web-api-eu
          image: ghcr.io/altinn/dialogporten-webapi:set-by-ci
          envFrom:
            - configMapRef:
                name: web-api-eu-runtime
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: Infrastructure__DialogDbConnectionString
              valueFrom:
                secretKeyRef:
                  name: web-api-eu-secrets
                  key: dialogportenAdoConnectionString
            - name: Infrastructure__Redis__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: web-api-eu-secrets
                  key: dialogportenRedisConnectionString
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-api-eu-runtime
  labels:
    app.kubernetes.io/name: web-api-eu
    app.kubernetes.io/part-of: dialogporten
data:
  AZURE_APPCONFIG_URI: ${DIALOGPORTEN_AZURE_APPCONFIG_URI}
  Infrastructure__MassTransit__Host: ${DIALOGPORTEN_SERVICEBUS_HOST}
  DIALOGPORTEN_ENVIRONMENT: set-by-env
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web-api-eu-secrets
  labels:
    app.kubernetes.io/name: web-api-eu
    app.kubernetes.io/part-of: dialogporten
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: dialogporten-azure-kv
  target:
    name: web-api-eu-secrets
    creationPolicy: Owner
  data:
    - secretKey: dialogportenAdoConnectionString
      remoteRef:
        key: dialogportenAdoConnectionString
    - secretKey: dialogportenRedisConnectionString
      remoteRef:
        key: dialogportenRedisConnectionString
---
apiVersion: v1
kind: Service
metadata:
  name: web-api-eu
  labels:
    app.kubernetes.io/name: web-api-eu
    app.kubernetes.io/part-of: dialogporten
spec:
  selector:
    app.kubernetes.io/name: web-api-eu
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web-api-eu
  labels:
    app.kubernetes.io/name: web-api-eu
    app.kubernetes.io/part-of: dialogporten
spec:
  routes:
    - match: PathPrefix(`/dialogporten/enduser`)
      priority: 10
      middlewares:
        - name: web-api-eu-ip-allowlist
      services:
        - name: web-api-eu
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: web-api-eu-ip-allowlist
  labels:
    app.kubernetes.io/name: web-api-eu
    app.kubernetes.io/part-of: dialogporten
spec:
  ipAllowList:
    sourceRange:
      - 0.0.0.0/32
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-api-eu
  labels:
    app.kubernetes.io/name: web-api-eu
    app.kubernetes.io/part-of: dialogporten
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-api-eu
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: application.dis.altinn.cloud/v1alpha1
kind: ApplicationIdentity
metadata:
  name: web-api-eu
  labels:
    app.kubernetes.io/name: web-api-eu
    app.kubernetes.io/part-of: dialogporten
spec: {}
