apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: dialogporten
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service
        app.kubernetes.io/part-of: dialogporten
    spec:
      serviceAccountName: service
      containers:
        - name: service
          image: ghcr.io/altinn/dialogporten-service:set-by-ci
          envFrom:
            - configMapRef:
                name: service-runtime
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: Infrastructure__DialogDbConnectionString
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: dialogportenAdoConnectionString
            - name: Infrastructure__Redis__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: dialogportenRedisConnectionString
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-runtime
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: dialogporten
data:
  AZURE_APPCONFIG_URI: ${DIALOGPORTEN_AZURE_APPCONFIG_URI}
  Infrastructure__MassTransit__Host: ${DIALOGPORTEN_SERVICEBUS_HOST}
  DIALOGPORTEN_ENVIRONMENT: set-by-env
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: service-secrets
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: dialogporten
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: dialogporten-azure-kv
  target:
    name: service-secrets
    creationPolicy: Owner
  data:
    - secretKey: dialogportenAdoConnectionString
      remoteRef:
        key: dialogportenAdoConnectionString
    - secretKey: dialogportenRedisConnectionString
      remoteRef:
        key: dialogportenRedisConnectionString
---
apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: dialogporten
spec:
  selector:
    app.kubernetes.io/name: service
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: service
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: dialogporten
spec:
  routes:
    - match: PathPrefix(`/dialogporten/service`)
      priority: 5
      middlewares:
        - name: service-ip-allowlist
      services:
        - name: service
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: service-ip-allowlist
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: dialogporten
spec:
  ipAllowList:
    sourceRange:
      - 0.0.0.0/32
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: dialogporten
spec:
  scaleTargetRef:
    name: service
---
apiVersion: application.dis.altinn.cloud/v1alpha1
kind: ApplicationIdentity
metadata:
  name: service
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: dialogporten
spec: {}
