apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: app
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/part-of: dialogporten
spec:
  entryPoints:
    - http
    - https
  routes:
    - kind: Rule
      match: Host(`placeholder.invalid`) && PathPrefix(`/dialogporten`)
      priority: 1
      middlewares:
        - name: app-ip-allowlist
      services:
        - name: app
          port: 80
