apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-resource-policy-information-job
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sync-resource-policy-information-job
              env:
                - name: DOTNET_ENVIRONMENT
                  value: prod
