apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/graphql/base
patches:
  - path: allowlist.yaml
  - path: deployment-env.yaml
  - path: deployment-resources.yaml
